In [ ]:
from google.colab import drive
drive.mount("/content/drive", force_remount=True)

Mounted at /content/drive


In [ ]:
FOLDERNAME = 'Colab\ Notebooks/Flower_project'
%cd drive/MyDrive/$FOLDERNAME 

/content/drive/MyDrive/Colab Notebooks/Flower_project


In [ ]:
%ls

My_FLOWERS102.ipynb  test/  train/  val/


In [ ]:
import torch
if torch.cuda.is_available():
  device = torch.device('cuda')
else:
  device = torch.device('cpu')

In [ ]:
device

device(type='cuda')

In [ ]:
from torchvision.transforms.transforms import RandomHorizontalFlip
# Load Existing Dataset                                            
train_data = None
val_data = None
import torchvision.datasets as dset
import torchvision.transforms as T
# from torchvision.transforms import functional as TF

transform = T.Compose([T.Resize((224,224)), T.ToTensor(), T.RandomHorizontalFlip(p=0.5), 
                       T.RandomAdjustSharpness(sharpness_factor=2), T.RandomAutocontrast(), 
                       T.ColorJitter(brightness=0.5, hue=0.3), 
                       T.Normalize((0.485, 0.456, 0.406), (0.229, 0.224, 0.225))])
transform_no_train = T.Compose([T.Resize((224,224)), T.ToTensor(), T.Normalize((0.485, 0.456, 0.406), (0.229, 0.224, 0.225))])

train_data = dset.Flowers102("./train", split = "test", download=True, transform=transform)
val_data = dset.Flowers102("./val", split='val', download=True, transform=transform_no_train)
test_data = dset.Flowers102("./test", split='train', download=True, transform=transform_no_train)

In [ ]:
# import os
# folders = os.listdir('102flowers/jpg/')
# print(folders)
# print(len(folders))                         # 8189
# all_img = dset.ImageFolder('102flowers/')
# print(all_img.class_to_idx)             # {'102flowers (1)': 0}

In [ ]:
import scipy.io

In [ ]:
img_labels = scipy.io.loadmat("train/flowers-102/imagelabels.mat")
img_labels = img_labels["labels"]
img_labels = img_labels[0]
# img_labels
print(img_labels)

[77 77 77 ... 62 62 62]


In [ ]:
iterable_train = iter(train_data)
tensors_train, labels_train = next(iterable_train)
tensors_train, labels_train

(tensor([[[-2.0922, -1.9382, -0.9883,  ..., -0.7572, -0.6032, -0.6288],
          [-2.0922, -1.9125, -1.1423,  ..., -0.5775, -0.5910, -0.6223],
          [-2.0922, -1.8868, -1.5531,  ..., -0.5766, -0.6022, -0.6078],
          ...,
          [-2.0922, -2.1179, -2.1179,  ..., -1.8612, -1.8868, -1.9125],
          [-2.0666, -2.0922, -2.0666,  ..., -1.8098, -1.8868, -1.9125],
          [-2.0666, -2.0922, -2.0666,  ..., -1.8098, -1.8868, -1.9125]],
 
         [[-0.6709, -0.8809, -0.4084,  ..., -0.4347, -0.2772, -0.3034],
          [-0.7234, -0.8546, -0.5230,  ..., -0.2772, -0.3034, -0.3034],
          [-0.8021, -0.8546, -0.9281,  ..., -0.2772, -0.2772, -0.2772],
          ...,
          [-1.5633, -1.5895, -1.6158,  ..., -1.0646, -1.0908, -1.1171],
          [-1.5633, -1.5895, -1.6420,  ..., -1.0646, -1.1433, -1.1958],
          [-1.5633, -1.5895, -1.6420,  ..., -1.0646, -1.1433, -1.1958]],
 
         [[-0.9126, -0.9140, -0.1862,  ..., -0.4000, -0.2433, -0.2694],
          [-0.8979, -0.8357,

In [ ]:
# Check data dimension

print(train_data)
# print(train_data[0][0])
print(train_data[0][0].shape)
print('= ='*30)
print(val_data)
# print(val_data[0][0])
print(val_data[0][0].shape)

Dataset Flowers102
    Number of datapoints: 6149
    Root location: ./train
    split=test
    StandardTransform
Transform: Compose(
               Resize(size=(224, 224), interpolation=bilinear, max_size=None, antialias=None)
               ToTensor()
               RandomHorizontalFlip(p=0.5)
               RandomAdjustSharpness(sharpness_factor=2,p=0.5)
               RandomAutocontrast(p=0.5)
               ColorJitter(brightness=[0.5, 1.5], contrast=None, saturation=None, hue=[-0.3, 0.3])
               Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225))
           )
torch.Size([3, 224, 224])
= == == == == == == == == == == == == == == == == == == == == == == == == == == == == == =
Dataset Flowers102
    Number of datapoints: 1020
    Root location: ./val
    split=val
    StandardTransform
Transform: Compose(
               Resize(size=(224, 224), interpolation=bilinear, max_size=None, antialias=None)
               ToTensor()
               Normalize(mean=(0.485, 0

In [ ]:
train_data[0][0]

tensor([[[-2.0929, -1.9430, -1.0183,  ..., -0.7882, -0.6377, -0.6628],
         [-2.0929, -1.9180, -1.1683,  ..., -0.6126, -0.6377, -0.6628],
         [-2.0929, -1.8930, -1.5681,  ..., -0.6628, -0.6628, -0.6879],
         ...,
         [-2.0929, -2.1179, -2.1179,  ..., -1.8680, -1.8930, -1.9180],
         [-2.0679, -2.0929, -2.0679,  ..., -1.8180, -1.8930, -1.9180],
         [-2.0679, -2.0929, -2.0679,  ..., -1.8180, -1.8930, -1.9180]],

        [[-0.7955, -1.0599, -0.5948,  ..., -0.4275, -0.2639, -0.2912],
         [-0.8937, -1.0835, -0.7400,  ..., -0.2639, -0.2912, -0.2912],
         [-0.9768, -1.1176, -1.1879,  ..., -0.2639, -0.2639, -0.2639],
         ...,
         [-1.6436, -1.6714, -1.6820,  ..., -1.0817, -1.1089, -1.1362],
         [-1.6265, -1.6542, -1.6840,  ..., -1.0817, -1.1634, -1.2180],
         [-1.6265, -1.6542, -1.6840,  ..., -1.0817, -1.1634, -1.2214]],

        [[-0.4476, -0.6647, -0.1762,  ..., -0.3053, -0.1450, -0.1718],
         [-0.5019, -0.6375, -0.2848,  ..., -0

In [ ]:
# create mini batches
from torch.utils.data import DataLoader
mini_trains = DataLoader(train_data, batch_size=10, shuffle=True)
mini_vals = DataLoader(val_data, batch_size=10, shuffle=True)
mini_trains

In [ ]:
from collections.abc import Iterable
iterable = iter(mini_trains)
tensors, labels = next(iterable)
tensors, labels                           # true labels 有10笔

(tensor([[[[-1.7039e+00, -1.7283e+00, -1.7526e+00,  ..., -4.1323e-01,
            -5.3500e-01, -6.0805e-01],
           [-1.5822e+00, -1.6383e+00, -1.6140e+00,  ..., -2.1280e-01,
            -3.5704e-01, -4.1323e-01],
           [-1.5091e+00, -1.5334e+00, -1.4585e+00,  ...,  1.0191e-01,
             2.6982e-02,  7.5690e-04],
           ...,
           [-1.8013e+00, -1.8100e+00, -1.9268e+00,  ..., -1.9006e+00,
            -1.9325e+00, -1.8744e+00],
           [-1.8013e+00, -1.8500e+00, -1.9774e+00,  ..., -1.7582e+00,
            -1.8238e+00, -1.8257e+00],
           [-1.6552e+00, -1.7039e+00, -1.7283e+00,  ..., -1.5822e+00,
            -1.6309e+00, -1.6796e+00]],
 
          [[-8.6560e-01, -8.9050e-01, -8.6560e-01,  ...,  2.4286e+00,
             2.4286e+00,  2.3958e+00],
           [-7.1623e-01, -7.4495e-01, -7.2389e-01,  ...,  2.4286e+00,
             2.4286e+00,  2.4286e+00],
           [-5.9175e-01, -5.7068e-01, -5.7260e-01,  ...,  2.4286e+00,
             2.4286e+00,  2.4286e+00],


In [ ]:
from torchvision import models
import torch.nn as nn
import torch.optim as optim
resnet = models.resnet152(pretrained=True).cuda()
num_flatten = resnet.fc.in_features
resnet.fc = nn.Linear(num_flatten, 102)
model = resnet.to(device)
optimizer = optim.Adam(model.parameters(), lr=1e-4)

In [ ]:
def evaluate(model, mini_vals):
  model.eval()
  with torch.no_grad():
    total_acc = 0
    for x, y in mini_vals:
      x = x.to(device)
      y = y.to(device)
      scores = model(x)
      predictions = scores.max(1)[1]
      acc = predictions.eq(y).sum().item()
      total_acc += acc
    print('Acc:', total_acc/len(val_data))


In [ ]:
# training data
NUM_EPOCHS = 2
print_every = 25
for epoch in range (NUM_EPOCHS):
  for counter, (x, y) in enumerate(mini_trains):
    # Turn on training mode
    model.train()
    # Move data to the corresponding device
    x = x.to(device)
    y = y.to(device)
    # ForwardProp
    scores = model(x)
    # Calculate Loss
    loss_function = nn.CrossEntropyLoss()
    loss = loss_function(scores, y)
    if counter % print_every == 0:
      print('Epoch', epoch, loss.item(), end=' / ')
      evaluate(model, mini_vals)
    # Clear previous gradient
    optimizer.zero_grad()
    # BackProp
    loss.backward()
    # Update Parameters
    optimizer.step()

Epoch 0 4.771821022033691 / Acc: 0.012745098039215686
Epoch 0 4.072345733642578 / Acc: 0.09019607843137255
Epoch 0 3.3488051891326904 / Acc: 0.1264705882352941
Epoch 0 3.7441916465759277 / Acc: 0.16176470588235295
Epoch 0 2.914599895477295 / Acc: 0.24509803921568626
Epoch 0 2.674734592437744 / Acc: 0.3127450980392157
Epoch 0 3.169422149658203 / Acc: 0.3627450980392157
Epoch 0 2.2730519771575928 / Acc: 0.3803921568627451
Epoch 0 1.3979380130767822 / Acc: 0.43137254901960786
Epoch 0 1.4750888347625732 / Acc: 0.48137254901960785
Epoch 0 1.4148623943328857 / Acc: 0.4852941176470588
Epoch 0 1.9372631311416626 / Acc: 0.5029411764705882
Epoch 0 1.2849749326705933 / Acc: 0.5303921568627451
Epoch 0 1.433327555656433 / Acc: 0.5617647058823529
Epoch 0 1.7938810586929321 / Acc: 0.5990196078431372
Epoch 0 1.1097760200500488 / Acc: 0.6225490196078431
Epoch 0 0.8204770088195801 / Acc: 0.6098039215686275
Epoch 0 1.434106707572937 / Acc: 0.6666666666666666
Epoch 0 0.6077212691307068 / Acc: 0.6823529411